
export const editions = {
  federal: {
    name: 'Federal Flow Clerk Basic',
    slug: 'federal-flow',
    tagline: 'Formal, compliant, serif‑first for government‑grade clarity.',
    palette: {
      primary: '#1B3A6B',
      secondary: '#2E5090',
      accent: '#4A7BA7',
      success: '#2D5016',
      bg: '#FFFFFF',
      card: '#F5F7FA',
      text: '#0A0E27',
      muted: '#5A6B7D',
      border: '#D4DCE6',
    },
    hero: 'Formal Government Documents',
    description: 'Trusted by federal agencies and legal teams.',
    features: ['Serif-first typography', 'Compliance-ready spacing', 'Multi-level clearance marks'],
    icon: '📋',
  },
  clerical: {
    name: 'Clerical Pro',
    slug: 'clerical-pro',
    tagline: 'Modern office polish with crisp sans and restrained accents.',
    palette: {
      primary: '#2F5597',
      secondary: '#385D8A',
      accent: '#64748B',
      success: '#16A34A',
      bg: '#FFFFFF',
      card: '#F8FAFC',
      text: '#0F172A',
      muted: '#64748B',
      border: '#E2E8F0',
    },
    hero: 'Professional Office Docs',
    description: 'Clean, contemporary style for corporate teams.',
    features: ['Modern sans-serif', 'Subtle color accents', 'Quick style sets'],
    icon: '💼',
  },
  tech: {
    name: 'Tech Code',
    slug: 'tech-code',
    tagline: 'Developer‑friendly with monospaced code styles and syntax palette.',
    palette: {
      primary: '#0F172A',
      secondary: '#1E293B',
      accent: '#06B6D4',
      success: '#10B981',
      bg: '#FFFFFF',
      card: '#F1F5F9',
      text: '#0F172A',
      muted: '#64748B',
      border: '#CBD5E1',
    },
    hero: 'Developer & Tech Docs',
    description: 'Code blocks, syntax highlighting, and technical clarity.',
    features: ['Monospaced code blocks', 'Syntax palette', 'Callout styles for APIs'],
    icon: '💻',
  },
  wiki: {
    name: 'Wiki Guidelines',
    slug: 'wiki-guidelines',
    tagline: 'Collaborative readability, accessible colors, and TOC emphasis.',
    palette: {
      primary: '#4F7328',
      secondary: '#5F9B2E',
      accent: '#84CC16',
      success: '#22C55E',
      bg: '#FFFFFF',
      card: '#F7FEE7',
      text: '#1B1F0B',
      muted: '#6B7280',
      border: '#D4D4D8',
    },
    hero: 'Collaborative Knowledge Docs',
    description: 'Inclusive design for team wikis and documentation.',
    features: ['Accessible color palette', 'TOC emphasis', 'Collaborative formatting'],
    icon: '📚',
  },
};

export type Edition = typeof editions[keyof typeof editions];
export type EditionKey = keyof typeof editions;
